"""Offline tests for the provenance-carrying raw data loader.

The committed fixture is regenerated by copying the header and the first 30 source
rows for each (year, sex) pair where year is 1880 or 1881, preserving source order.
"""

import hashlib
import subprocess
import sys
from pathlib import Path

import pytest

from namegender.data import (
    REQUIRED_COLUMNS,
    EXPECTED_SEX_VALUES,
    SOURCE_URL,
    download_raw,
    load_raw,
    verify_integrity,
)
from namegender.errors import DataError, IntegrityError, SchemaError

FIXTURE = Path(__file__).parent / "fixtures" / "baby_names_sample.csv"


def _write_csv(tmp_path, text):
    path = tmp_path / "malformed.csv"
    path.write_text('"year","name","percent","sex"\n' + text)
    return path


def test_fixture_has_required_columns_and_rows():
    frame = load_raw(FIXTURE)
    assert list(frame.columns) == list(REQUIRED_COLUMNS)
    assert len(frame) > 0


def test_fixture_sexes_are_expected():
    assert set(load_raw(FIXTURE)["sex"].unique()) <= EXPECTED_SEX_VALUES


def test_missing_column_raises_schema_error(tmp_path):
    path = tmp_path / "missing.csv"
    path.write_text('"year","name","percent"\n1880,"Alex",0.5\n')
    with pytest.raises(SchemaError):
        load_raw(path)


def test_unexpected_sex_raises_schema_error(tmp_path):
    with pytest.raises(SchemaError):
        load_raw(_write_csv(tmp_path, '1880,"Alex",0.5,"unknown"\n'))


@pytest.mark.parametrize("percent", [0.0, -0.1, 1.01])
def test_invalid_percent_raises_schema_error(tmp_path, percent):
    with pytest.raises(SchemaError):
        load_raw(_write_csv(tmp_path, f'1880,"Alex",{percent},"boy"\n'))


def test_invalid_year_raises_schema_error(tmp_path):
    with pytest.raises(SchemaError):
        load_raw(_write_csv(tmp_path, '1879,"Alex",0.5,"boy"\n'))


def test_null_required_value_raises_schema_error(tmp_path):
    with pytest.raises(SchemaError):
        load_raw(_write_csv(tmp_path, '1880,,0.5,"boy"\n'))


def test_whitespace_name_raises_schema_error(tmp_path):
    with pytest.raises(SchemaError):
        load_raw(_write_csv(tmp_path, '1880,"   ",0.5,"boy"\n'))


def test_integrity_rejects_wrong_hash_and_byte_count(tmp_path):
    path = tmp_path / "data.csv"
    path.write_bytes(b"fixture")
    with pytest.raises(IntegrityError, match="expected SHA-256"):
        verify_integrity(path, expected_sha256="0" * 64)
    with pytest.raises(IntegrityError, match="expected bytes"):
        verify_integrity(path, expected_bytes=999)


def test_integrity_accepts_fixture_digest_and_size():
    content = FIXTURE.read_bytes()
    verify_integrity(
        FIXTURE,
        expected_sha256=hashlib.sha256(content).hexdigest(),
        expected_bytes=len(content),
    )


def test_missing_path_raises_data_error(tmp_path):
    with pytest.raises(DataError):
        load_raw(tmp_path / "does-not-exist.csv")


def test_download_raw_works_offline_with_file_url(tmp_path, monkeypatch):
    import namegender.data as data_module

    content = FIXTURE.read_bytes()
    monkeypatch.setattr(data_module, "EXPECTED_SHA256", hashlib.sha256(content).hexdigest())
    monkeypatch.setattr(data_module, "EXPECTED_BYTES", len(content))
    destination = tmp_path / "nested" / "download.csv"
    result = download_raw(destination, url=FIXTURE.resolve().as_uri())
    assert result == destination
    assert destination.read_bytes() == content


def test_download_raw_removes_temporary_file_when_integrity_fails(tmp_path, monkeypatch):
    import namegender.data as data_module

    source = tmp_path / "source.csv"
    source.write_bytes(b"completed download with invalid integrity")
    monkeypatch.setattr(data_module, "EXPECTED_SHA256", "0" * 64)
    monkeypatch.setattr(data_module, "EXPECTED_BYTES", len(source.read_bytes()))
    destination = tmp_path / "download.csv"

    with pytest.raises(IntegrityError):
        download_raw(destination, url=source.resolve().as_uri())

    assert not destination.exists()
    assert list(tmp_path.glob(f".{destination.name}.*")) == []


def test_default_load_checks_integrity_before_parsing(tmp_path, monkeypatch):
    import namegender.data as data_module

    copied_fixture = tmp_path / "baby-names.csv"
    copied_fixture.write_bytes(FIXTURE.read_bytes())
    assert len(load_raw(copied_fixture)) > 0  # Schema validation alone accepts this copy.

    monkeypatch.setattr(data_module, "default_raw_path", lambda: copied_fixture)
    with pytest.raises(IntegrityError):
        load_raw()


def test_importing_data_does_not_create_socket():
    src_path = Path(__file__).resolve().parents[1] / "src"
    script = f"""
import urllib.request
import socket
def blocked_connection(*args, **kwargs):
    raise AssertionError('network connection')
socket.socket.connect = blocked_connection
socket.create_connection = blocked_connection
import sys
sys.path.insert(0, {str(src_path)!r})
import namegender.data
assert namegender.data.SOURCE_URL == {SOURCE_URL!r}
"""
    result = subprocess.run([sys.executable, "-c", script], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
